include:
  - board: seeeduino_xiao_ble
    shield: strugglestick

# name: Build ZMK firmware
# on: [push, pull_request, workflow_dispatch]

# name: Build ZMK firmware
# on: [push, pull_request, workflow_dispatch]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ZMK
#         uses: actions/checkout@v3
#         with:
#           repository: zmkfirmware/zmk
#           ref: main
#           path: zmk

#       - name: Checkout User Config
#         uses: actions/checkout@v3
#         with:
#           path: config

#       - name: Set Up Zephyr Environment
#         run: |
#           west init -l config
#           west update

#       - name: Patch Zephyr ADC Oversampling
#         run: |
#           sed -i 's/uint8_t oversampling;/uint8_t oversampling = 0;/g' zephyr/include/drivers/adc.h

#       - name: Build Firmware
#         run: |
#           west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=strugglestick

# name: Build ZMK firmware
# on: [push, pull_request, workflow_dispatch]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       # Step 1: Checkout ZMK
#       - name: Checkout ZMK
#         uses: actions/checkout@v3
#         with:
#           repository: zmkfirmware/
#           ref: main
#           path: zmk

#       # Step 2: Checkout User Config
#       - name: Checkout User Config
#         uses: actions/checkout@v3
#         with:
#           path: config

#       # Step 3: Set Up Zephyr Environment
#       - name: Set Up Zephyr Environment
#         run: |
#           west init -l config
#           west update

#       # Step 4: Verify Zephyr Source Code
#       - name: Verify Zephyr Source Code
#         run: |
#           if [ ! -d "zephyr" ]; then
#             echo "Error: Zephyr source code not found!"
#             exit 1
#           fi

#       # Step 5: Patch Zephyr ADC Oversampling
#       - name: Patch Zephyr ADC Oversampling
#         run: |
#           sed -i 's/uint8_t oversampling;/uint8_t oversampling = 0;/g' zephyr/include/drivers/adc.h

#       # Step 6: Build Firmware
#       - name: Build Firmware
#         run: |
#           west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=strugglestick
