file_format: "1"
id: Ed1tor50
name: Ed1tor50
type: shield
url: https://boardsource.xyz/store/5ecc2008eee64242946c98c1
requires: [seeeduino_xiao_ble]
features:
  - keys
  - studio
  - pointer
  - encoder
  - underglow
