layout: {zmk_keyboard: Ed1tor50}
layers:
  QWERTY:
  - TAB
  - Q
  - W
  - E
  - R
  - T
  - '&td0'
  - A
  - S
  - D
  - F
  - G
  - LCTRL
  - Z
  - X
  - C
  - V
  - B
  - '&mkp LCLK'
  - ESC
  - SYMBOL
  - LGUI
  - '&rgblayer RGB_COLOR_HSB_VAL(0,95,45) 1'
  - {t: SPACE, h: Fn}
  - Fn
  - BSPC
  - '&rgblayer RGB_COLOR_HSB_VAL(0,87,50) 1'
  - O
  - I
  - U
  - Y
  - ''''
  - ;
  - L
  - K
  - J
  - H
  - RSHFT
  - /
  - .
  - ','
  - M
  - N
  - '&mkp RCLK'
  - PSCRN
  - SYMBOL
  - RALT
  - SYMBOL
  - {t: ENTER, h: Fn}
  NUMBER:
  - {t: ▽, type: trans}
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - {t: ▽, type: trans}
  - BT CLR ALL
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: ▽, type: trans}
  - RGB OFF
  - RGB ON
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - RGB EFF
  - '&mkp LCLK'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Fn
  - BSPC
  - '0'
  - '9'
  - '8'
  - '7'
  - '6'
  - PG UP
  - HOME
  - RIGHT
  - UP
  - DOWN
  - LEFT
  - PG DN
  - END
  - RGB BRD
  - RGB BRI
  - RGB SPI
  - RGB EFR
  - '&mkp RCLK'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - DEL
  - INS
  SYMBOL:
  - {t: ▽, type: trans}
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - {t: ▽, type: trans}
  - BT CLR
  - '&mkp LCLK'
  - '&mkp MCLK'
  - '&mkp RCLK'
  - '&mkp MB4'
  - {t: ▽, type: trans}
  - OUT USB
  - OUT BLE
  - ''
  - ''
  - '&mkp MB5'
  - '&mkp LCLK'
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - SPACE
  - Fn
  - BSPC
  - )
  - (
  - '*'
  - '&'
  - ^
  - '`'
  - \
  - ']'
  - '['
  - '='
  - '-'
  - '~'
  - '|'
  - '}'
  - '{'
  - +
  - _
  - '&mkp RCLK'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - RET
  Fn:
  - '&studio_unlock'
  - F1
  - F2
  - F3
  - F4
  - F5
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&mkp LCLK'
  - '&mkp MCLK'
  - '&mkp RCLK'
  - '&mkp MB4'
  - {t: ▽, type: trans}
  - '&sys_reset'
  - {t: ▽, type: trans}
  - '&bootloader'
  - {t: ▽, type: trans}
  - '&mkp MB5'
  - '&mkp LCLK'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - Fn
  - F11
  - F10
  - F9
  - F8
  - F7
  - F6
  - F12
  - PRINTSCREEN
  - RCLK
  - MCLK
  - LCLK
  - '&bootloader'
  - PAUSE BREAK
  - SCROLLLOCK
  - '&sys_reset'
  - '&bootloader'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '&mkp RCLK'
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
