manifest:
  remotes:
    - name: jjggzhou
      url-base: https://github.com/jjggzhou
    - name: jjggzhou
      url-base: https://github.com/jjggzhou
    - name: urob
      url-base: https://github.com/urob
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: zmk
      remote: jjggzhou
      revision: main
      import: app/west.yml
    - name: zmk-analog-input-driver
      remote: jjggzhou
      revision: main
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-tri-state
      remote: urob
      revision: main
    - name: zmk-driver-animation
      remote: cormoran
      revision: main
    - name: zmk-driver-ext-power-transient
      remote: cormoran
      revision: main
  self:
    path: config





# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#     - name: badjeff
#       url-base: https://github.com/badjeff/
#     - name: yourgithub
#       url-base: https://github.com/yourgithub/
#   projects:
#     - name: zmk
#       remote: zmkfirmware
#       revision: main
#       import: app/west.yml
#     - name: zmk-analog-input-driver
#       remote: badjeff
#       revision: main
#     - name: zephyr
#       remote: yourgithub
#       revision: main
#   self:
#     path: config
