manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jjggzhou
      url-base: https://github.com/jjggzhou
    - name: urob
      url-base: https://github.com/urob
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-analog-input-driver
      remote: jjggzhou
      revision: 1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t  # Replace with a known good commit hash
    - name: zmk-auto-layer
      remote: urob
      revision: main
    - name: zmk-tri-state
      remote: urob
      revision: main
  self:
    path: config





# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#     - name: badjeff
#       url-base: https://github.com/badjeff/
#     - name: yourgithub
#       url-base: https://github.com/yourgithub/
#   projects:
#     - name: zmk
#       remote: zmkfirmware
#       revision: main
#       import: app/west.yml
#     - name: zmk-analog-input-driver
#       remote: badjeff
#       revision: main
#     - name: zephyr
#       remote: yourgithub
#       revision: main
#   self:
#     path: config
